name: Setup Environment
description: Setup for test & build
inputs:
  token:
    description: "Personal Access Token"
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node
      id: setup_node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache node_modules
      id: cache_node_modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Install dependencies
      if: ${{ steps.cache_node_modules.outputs.cache-hit != 'true' }}
      run: |
        pnpm i --frozen-lockfile
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.token }}
