name: Deploy to Cloudflare Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubicloud
    timeout-minutes: 5
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: gacha-comp
          directory: ./out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
